-- AlterTable
ALTER TABLE "Player" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "createdBy" TEXT;

-- AlterTable
ALTER TABLE "Club" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "createdBy" TEXT;

-- AlterTable
ALTER TABLE "Competition" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN "createdBy" TEXT;

-- AlterTable
ALTER TABLE "Question" ADD COLUMN "createdBy" TEXT;
